# Generated by Django 4.1.6 on 2023-02-24 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_books_options_books_time_create_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='time_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
