# Generated by Django 4.1.6 on 2023-02-08 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='genre_id',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='book_id',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='parent_comment_id',
            new_name='parent_comment',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='role_id',
            new_name='role',
        ),
    ]
